agence/agence/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.flatpages import views




urlpatterns = patterns('',
	url(r'^$', views.flatpage, {'url': '/'}, name='home'),	
    url(r'^catalog/', include('catalogue.urls', namespace="catalog")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^photologue/', include('photologue.urls', namespace='photologue')),
    url(r'^accounts/login/$', auth_views.login),
    url(r'^contact/$', views.flatpage, {'url': '/contact/'}, name='contact'),
    #url(r'^$', views.flatpage, {'url': '/home/'}, name='home'),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agence/catalogue/urls.py
from django.conf.urls import patterns, url

from catalogue import views

urlpatterns = patterns('',
   
   
   url(r'^$', views.index, name='index'),
   url(r'^company/(?P<company_id>\d+)/$', views.detail_company, name='detail_company'),
   url(r'^scene/(?P<scene_id>\d+)/$', views.detail_scene, name='detail_scene'),   
   url(r'^pro/', views.pro, name='pro'),  
   url(r'^proLight/', views.proLight, name='proLight'), 
   url(r'^newsletter/', views.newsletter, name='newsletter'), 
   
)

agence/catalogue/models.py
from django.db import models
from photologue.models import Gallery, Photo

class SceneCat(models.Model):
    category = models.CharField(max_length=200)

    def __unicode__(self):
	return self.category


class Age(models.Model):
    category = models.CharField(max_length=200)

    def __unicode__(self):
	   return self.category

class Duration(models.Model):
    hour = models.IntegerField(blank=True, null=True)
    minute = models.IntegerField(blank=True, null=True)
    condition = models.CharField(max_length=200, blank=True, null=True)    

    def __unicode__(self):
    	hour = str(self.hour)
    	minute = str(self.minute)
    	if self.hour != None:
            hour = str(self.hour)
            if self.hour > 1 and self.hour != 0:
                descH = "heures"
            else:
                descH = "heure"
        else:
            hour = ""
            descH = ""
        if self.minute  != None:
            minute = str(self.minute)
            if self.minute > 1 and self.minute != 0:
                descM = "minutes"
            else:
                descM = "minute"
        else:
            minute = ""
            descM = ""
        if self.condition == None and self.hour == None and self.minute == None :
            duration = ""
        else:
            duration = " ".join([hour,descH, minute,descM, self.condition])
        return duration

class Partnership(models.Model):
    name = models.CharField(max_length=200)
    logo = models.ForeignKey(Photo, blank=True, null=True)
    url = models.CharField(blank=True, max_length=200, null=True)
    
    def __unicode__(self):
	   return self.name

class Company(models.Model):
    name = models.CharField(max_length=200)
    resume = models.TextField(blank=True, null=True)
    workshop_descr = models.TextField(blank=True, null=True)
    workshop_price = models.IntegerField(blank=True, null=True)
    workshop_term = models.CharField(blank=True, max_length=200, null=True)
    logo = models.ForeignKey(Photo, blank=True, null=True)
    photo_gallery = models.ForeignKey(Gallery, blank=True, null=True)

    def __unicode__(self):
    	return self.name
  
class Scene(models.Model):
    company = models.ForeignKey(Company)
    title = models.CharField(max_length=200, null=True)
    scene_cat =  models.ManyToManyField(SceneCat, blank=True, null=True)
    synops = models.TextField(blank=True, null=True)
    interpret = models.CharField(blank=True, max_length=500, null=True)
    age = models.ForeignKey(Age, blank=True, null=True)
    duration = models.ForeignKey(Duration, blank=True, null=True)
    full_price = models.IntegerField(blank=True, null=True)
    full_nb_people = models.IntegerField(blank=True, null=True)
    light_price = models.IntegerField(blank=True, null=True)
    light_nb_people = models.IntegerField(blank=True, null=True)
    teazer_url = models.CharField(blank=True, max_length=200, null=True)
    disponibility = models.CharField(blank=True, max_length=200, null=True)
    photo_gallery = models.ForeignKey(Gallery, blank=True, null=True)    
    dossier_presse = models.FileField(upload_to="dossiers_presse/", null=True, blank=True)
    dossier_peda = models.FileField(upload_to="dossiers_peda/", null=True, blank=True)
    archive_zip = models.FileField(upload_to="archives_zip/", null=True, blank=True)
    technic_file = models.FileField(upload_to="fiche_tech/", null=True, blank=True)
    full_jauge = models.IntegerField(blank=True, null=True)
    plateau_min_size = models.IntegerField(blank=True, null=True)
    representation_site = models.TextField(blank=True, null=True)
    electric_need = models.CharField(blank=True, max_length=200, null=True)
 
    def __unicode__(self):             
        return self.title

agence/catalogue/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django_tables2   import RequestConfig
from catalogue.models import Company, Scene, SceneTableFull, SceneTableLight
from photologue.models import Gallery, Photo



@login_required
def pro(request):
	 scene_table = SceneTableFull(Scene.objects.order_by('title'))
	 RequestConfig(request, paginate=False).configure(scene_table)
	 pro = True
	 return render(request, 'catalogue/pro.html', {'scene_table': scene_table, 'pro':pro})

@login_required
def proLight(request):
	 scene_table = SceneTableLight(Scene.objects.order_by('title'))
	 RequestConfig(request, paginate=False).configure(scene_table)
	 pro = False
	 return render(request, 'catalogue/pro.html', {'scene_table': scene_table, 'pro':pro})

def newsletter(request):
	return render(request, 'catalogue/newsletter.html')

def index(request):
	company_list = Company.objects.order_by('name')
	scene_list = Scene.objects.order_by('title')
	cover = Photo.objects.filter(title='cover')
	scene_photo_list = []
	for scene in scene_list:
		if scene.photo_gallery:
			if scene.photo_gallery.photos:
				scene_photo_list.append(scene)
	return render(request, 'catalogue/index.html', {'company_list':  company_list, 'scene_list': scene_list, 'scene_photo_list':scene_photo_list, 'cover': cover})

def detail_company(request, company_id):

    company = get_object_or_404(Company,pk=company_id)
    scene_list = company.scene_set.all()
    cover = Photo.objects.filter(title='cover_'+company.name)
    try:
       gallery = Gallery.objects.get(pk=company.photo_gallery_id)
    except Gallery.DoesNotExist:
       gallery = None
    return render(request, 'catalogue/detail.html', {'company': company, 'gallery': gallery, 'scene_list': scene_list, 'cover': cover})

def detail_scene(request, scene_id):
    scene = get_object_or_404(Scene, pk=scene_id)
    cover = Photo.objects.filter(title='cover_'+scene.title)
    try:
       gallery = Gallery.objects.get(pk=scene.photo_gallery_id)
    except Gallery.DoesNotExist:
       gallery = None
   
    return render(request, 'scene/detail.html', {'scene':scene, 'gallery': gallery, 'cover': cover})

agence/catalogue/templates/base/base.html
<!DOCTYPE HTML>
<html>
<head>
  <title>L'ageNCe</title>
</head>
<body style="overflow-x: visible; padding-top: 0px;">
 
  <nav class="navbar navbar-inverse navbar-fixed-top" style="margin-bottom: 0px;">
    <div class="container-fluid">
              <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home' %}">AgeNCe</a>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-controls="navbar">                  
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
              </div>
              <div id="navbar" class="navbar-collapse collapse" >
                <ul class="nav navbar-nav right" >                  
                  <li><a href="{% url 'catalog:index' %}">Catalogue</a></li>
                  <li><a href="{% url 'catalog:pro' %}">Acces Pro</a></li>
                  <li><a href="{% url 'contact' %}">Contact</a></li>
                  <li><a href="{% url 'catalog:newsletter' %}">Newsletter</a></li>
                </ul>
              </div>
            </div>
  </nav>
            
  <div id="container"  class="site-wrapper" style="padding-top: 50px;">      
    <div class="site-wrapper">

      <div class="site-wrapper-inner">
        
              
        {% block home %}
        {% endblock home %}
        </div><!-- class="cover-container"-->
        {% block content %}
        {% endblock content %}
      </div><!-- class="site-wrapper-inner"-->
    </div><!-- class="site-wrapper"-->     
    <div id="footer" style=" padding-bottom: 10px; ">
      {% block footer %}
      {% include "./base/footer.html" %}
      {% endblock %}
      {% load staticfiles %}
      {% block css %}
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
      <link rel="stylesheet" type="text/css" href="{% static 'catalogue/bootstrap/css/carousel.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'catalogue/bootstrap/css/offcanvas.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'catalogue/bootstrap/css/cover.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'catalogue/bootstrap/css/mytheme.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />
      {% endblock css %}  
      {% block js %}
     
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
      <script src="{% static 'catalogue/bootstrap/js/offcanvas.js' %}" ></script>
      {% endblock %}
    </div><!-- footer -->	

  </div><!-- container class="site-wrapper"  -->
</body>
</html>

agence/catalogue/templates/base/base_old.html
<!DOCTYPE HTML>
<html>
  <head>
    <title>L'ageNCe</title>
     
  </head>
  <body>
  {% block container %}
	<div id="container" >
		
        
      <div id="header">
    		<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      		<div class="container">
        		<div class="navbar-header">
				      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				        <span class="sr-only">Toggle navigation</span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				      </button>
				      <a class="navbar-brand" href="/">AgeNCe</a>
				    </div><!-- /.nav-header -->
				    
		      	<div class="collapse navbar-collapse">
				      <ul class="nav navbar-nav">
				        <li class="{% block link_home_class %}{% endblock %}"><a href="{% url 'catalog:index' %}">Catalogue</a></li>
				      </ul>
		  	    </div><!-- /.nav-collapse -->
		  	          
      		</div><!-- /.container -->
      	</div><!-- /.navbar -->
    	</div><!-- /.header -->
     
    <div class="container-fluid" id="content">
        {% block content %}
        {% endblock content %}
    </div><!-- content -->
   {% endblock container %}
     
		<div id="footer">
        {% block footer %}
        {% include "./base/footer.html" %}
        {% endblock %}
        {% load staticfiles %}
    		{% block css %}
   			<link rel="stylesheet" type="text/css" href="{% static 'catalogue/bootstrap/css/bootstrap.css' %}"/>
   			<link rel="stylesheet" type="text/css" href="{% static 'catalogue/bootstrap/css/carousel.css' %}" />
				<link rel="stylesheet" type="text/css" href="{% static 'catalogue/bootstrap/css/offcanvas.css' %}" />
    		{% endblock css %}  
        {% block js %}
        <script src="{% static 'catalogue/bootstrap/jquery/1.11.2/jquery-1.11.2.min.js' %}" ></script>
        <script src="{% static 'catalogue/bootstrap/js/bootstrap.js' %}" ></script>
        <script src="{% static 'catalogue/bootstrap/js/offcanvas.js' %}" ></script>
        {% endblock %}
      </div><!-- footer -->	
		
  </div><!-- container -->
  </body>
</html>

agence/catalogue/templates/base/footer.html
<div class="mastfoot" style="width: 100%">
	<p style="text-align: right; margin-right: 20px;">site edité par <a href="http://yogis.alwaysdata.net">YoGis</a></p>
</div>