agence/agence/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.flatpages import views




urlpatterns = patterns('',
	url(r'^$', views.flatpage, {'url': '/'}, name='home'),	
    url(r'^catalog/', include('catalogue.urls', namespace="catalog")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^photologue/', include('photologue.urls', namespace='photologue')),
    url(r'^accounts/login/$', auth_views.login),
    url(r'^contact/$', views.flatpage, {'url': '/contact/'}, name='contact'),
    #url(r'^$', views.flatpage, {'url': '/home/'}, name='home'),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agence/catalogue/urls.py
from django.conf.urls import patterns, url

from catalogue import views

urlpatterns = patterns('',
   
   
   url(r'^$', views.index, name='index'),
   url(r'^company/(?P<company_id>\d+)/$', views.detail_company, name='detail_company'),
   url(r'^scene/(?P<scene_id>\d+)/$', views.detail_scene, name='detail_scene'),   
   url(r'^pro/', views.pro, name='pro'),  
   url(r'^proLight/', views.proLight, name='proLight'), 
   url(r'^newsletter/', views.newsletter, name='newsletter'), 
   
)

agence/photologue/urls.py
from django.conf.urls import *
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from .views import PhotoListView, PhotoDetailView, GalleryListView, \
    GalleryDetailView, PhotoArchiveIndexView, PhotoDateDetailView, PhotoDayArchiveView, \
    PhotoYearArchiveView, PhotoMonthArchiveView, GalleryArchiveIndexView, GalleryYearArchiveView, \
    GalleryDateDetailView, GalleryDayArchiveView, GalleryMonthArchiveView, GalleryDateDetailOldView, \
    GalleryDayArchiveOldView, GalleryMonthArchiveOldView, PhotoDateDetailOldView, \
    PhotoDayArchiveOldView, PhotoMonthArchiveOldView

"""NOTE: the url names are changing. In the long term, I want to remove the 'pl-'
prefix on all urls, and instead rely on an application namespace 'photologue'.

At the same time, I want to change some URL patterns, e.g. for pagination. Changing the urls
twice within a few releases, could be confusing, so instead I am updating URLs bit by bit.

The new style will coexist with the existing 'pl-' prefix for a couple of releases.

"""


urlpatterns = patterns('',

                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                           GalleryDateDetailView.as_view(month_format='%m'),
                           name='gallery-detail'),
                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
                           GalleryDayArchiveView.as_view(month_format='%m'),
                           name='gallery-archive-day'),
                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
                           GalleryMonthArchiveView.as_view(month_format='%m'),
                           name='gallery-archive-month'),
                       url(r'^gallery/(?P<year>\d{4})/$',
                           GalleryYearArchiveView.as_view(),
                           name='pl-gallery-archive-year'),
                       url(r'^gallery/$',
                           GalleryArchiveIndexView.as_view(),
                           name='pl-gallery-archive'),
                       url(r'^$',
                           RedirectView.as_view(url=reverse_lazy('photologue:pl-gallery-archive')),
                           name='pl-photologue-root'),
                       url(r'^gallery/(?P<slug>[\-\d\w]+)/$',
                           GalleryDetailView.as_view(), name='pl-gallery'),
                       url(r'^gallerylist/$',
                           GalleryListView.as_view(),
                           name='gallery-list'),

                       url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                           PhotoDateDetailView.as_view(month_format='%m'),
                           name='photo-detail'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
                           PhotoDayArchiveView.as_view(month_format='%m'),
                           name='photo-archive-day'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
                           PhotoMonthArchiveView.as_view(month_format='%m'),
                           name='photo-archive-month'),
                       url(r'^photo/(?P<year>\d{4})/$',
                           PhotoYearArchiveView.as_view(),
                           name='pl-photo-archive-year'),
                       url(r'^photo/$',
                           PhotoArchiveIndexView.as_view(),
                           name='pl-photo-archive'),

                       url(r'^photo/(?P<slug>[\-\d\w]+)/$',
                           PhotoDetailView.as_view(),
                           name='pl-photo'),
                       url(r'^photolist/$',
                           PhotoListView.as_view(),
                           name='photo-list'),

                       # Deprecated URLs.
                       url(r'^gallery/page/(?P<page>[0-9]+)/$',
                           GalleryListView.as_view(),
                           {'deprecated_pagination': True},
                           name='pl-gallery-list'),
                       url(r'^photo/page/(?P<page>[0-9]+)/$',
                           PhotoListView.as_view(),
                           {'deprecated_pagination': True},
                           name='pl-photo-list'),

                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                           GalleryDateDetailOldView.as_view(),
                           name='pl-gallery-detail'),
                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$',
                           GalleryDayArchiveOldView.as_view(),
                           name='pl-gallery-archive-day'),
                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/$',
                           GalleryMonthArchiveOldView.as_view(),
                           name='pl-gallery-archive-month'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                           PhotoDateDetailOldView.as_view(),
                           name='pl-photo-detail'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$',
                           PhotoDayArchiveOldView.as_view(),
                           name='pl-photo-archive-day'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/$',
                           PhotoMonthArchiveOldView.as_view(),
                           name='pl-photo-archive-month')
                       )

agence/catalogue/models.py
from django.db import models
from photologue.models import Gallery, Photo

class SceneCat(models.Model):
    category = models.CharField(max_length=200)

    def __unicode__(self):
	return self.category


class Age(models.Model):
    category = models.CharField(max_length=200)

    def __unicode__(self):
	   return self.category

class Duration(models.Model):
    hour = models.IntegerField(blank=True, null=True)
    minute = models.IntegerField(blank=True, null=True)
    condition = models.CharField(max_length=200, blank=True, null=True)    

    def __unicode__(self):
    	hour = str(self.hour)
    	minute = str(self.minute)
    	if self.hour != None:
            hour = str(self.hour)
            if self.hour > 1 and self.hour != 0:
                descH = "heures"
            else:
                descH = "heure"
        else:
            hour = ""
            descH = ""
        if self.minute  != None:
            minute = str(self.minute)
            if self.minute > 1 and self.minute != 0:
                descM = "minutes"
            else:
                descM = "minute"
        else:
            minute = ""
            descM = ""
        if self.condition == None and self.hour == None and self.minute == None :
            duration = ""
        else:
            duration = " ".join([hour,descH, minute,descM, self.condition])
        return duration

class Partnership(models.Model):
    name = models.CharField(max_length=200)
    logo = models.ForeignKey(Photo, blank=True, null=True)
    url = models.CharField(blank=True, max_length=200, null=True)
    
    def __unicode__(self):
	   return self.name

class Company(models.Model):
    name = models.CharField(max_length=200)
    resume = models.TextField(blank=True, null=True)
    workshop_descr = models.TextField(blank=True, null=True)
    workshop_price = models.IntegerField(blank=True, null=True)
    workshop_term = models.CharField(blank=True, max_length=200, null=True)
    logo = models.ForeignKey(Photo, blank=True, null=True)
    photo_gallery = models.ForeignKey(Gallery, blank=True, null=True)

    def __unicode__(self):
    	return self.name
  
class Scene(models.Model):
    company = models.ForeignKey(Company)
    title = models.CharField(max_length=200, null=True)
    scene_cat =  models.ManyToManyField(SceneCat, blank=True, null=True)
    synops = models.TextField(blank=True, null=True)
    interpret = models.CharField(blank=True, max_length=500, null=True)
    age = models.ForeignKey(Age, blank=True, null=True)
    duration = models.ForeignKey(Duration, blank=True, null=True)
    full_price = models.IntegerField(blank=True, null=True)
    full_nb_people = models.IntegerField(blank=True, null=True)
    light_price = models.IntegerField(blank=True, null=True)
    light_nb_people = models.IntegerField(blank=True, null=True)
    teazer_url = models.CharField(blank=True, max_length=200, null=True)
    disponibility = models.CharField(blank=True, max_length=200, null=True)
    photo_gallery = models.ForeignKey(Gallery, blank=True, null=True)    
    dossier_presse = models.FileField(upload_to="dossiers_presse/", null=True, blank=True)
    dossier_peda = models.FileField(upload_to="dossiers_peda/", null=True, blank=True)
    archive_zip = models.FileField(upload_to="archives_zip/", null=True, blank=True)
    technic_file = models.FileField(upload_to="fiche_tech/", null=True, blank=True)
    full_jauge = models.IntegerField(blank=True, null=True)
    plateau_min_size = models.IntegerField(blank=True, null=True)
    representation_site = models.TextField(blank=True, null=True)
    electric_need = models.CharField(blank=True, max_length=200, null=True)
 
    def __unicode__(self):             
        return self.title

agence/catalogue/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django_tables2   import RequestConfig
from catalogue.models import Company, Scene, SceneTableFull, SceneTableLight
from photologue.models import Gallery, Photo



@login_required
def pro(request):
	 scene_table = SceneTableFull(Scene.objects.order_by('title'))
	 RequestConfig(request, paginate=False).configure(scene_table)
	 pro = True
	 return render(request, 'catalogue/pro.html', {'scene_table': scene_table, 'pro':pro})

@login_required
def proLight(request):
	 scene_table = SceneTableLight(Scene.objects.order_by('title'))
	 RequestConfig(request, paginate=False).configure(scene_table)
	 pro = False
	 return render(request, 'catalogue/pro.html', {'scene_table': scene_table, 'pro':pro})

def newsletter(request):
	return render(request, 'catalogue/newsletter.html')

def index(request):
	company_list = Company.objects.order_by('name')
	scene_list = Scene.objects.order_by('title')
	cover = Photo.objects.filter(title='cover')
	scene_photo_list = []
	for scene in scene_list:
		if scene.photo_gallery:
			if scene.photo_gallery.photos:
				scene_photo_list.append(scene)
	return render(request, 'catalogue/index.html', {'company_list':  company_list, 'scene_list': scene_list, 'scene_photo_list':scene_photo_list, 'cover': cover})

def detail_company(request, company_id):

    company = get_object_or_404(Company,pk=company_id)
    scene_list = company.scene_set.all()
    cover = Photo.objects.filter(title='cover_'+company.name)
    try:
       gallery = Gallery.objects.get(pk=company.photo_gallery_id)
    except Gallery.DoesNotExist:
       gallery = None
    return render(request, 'catalogue/detail.html', {'company': company, 'gallery': gallery, 'scene_list': scene_list, 'cover': cover})

def detail_scene(request, scene_id):
    scene = get_object_or_404(Scene, pk=scene_id)
    cover = Photo.objects.filter(title='cover_'+scene.title)
    try:
       gallery = Gallery.objects.get(pk=scene.photo_gallery_id)
    except Gallery.DoesNotExist:
       gallery = None
   
    return render(request, 'scene/detail.html', {'scene':scene, 'gallery': gallery, 'cover': cover})

agence/catalogue/templates/catalogue/carousel.html
<!-- Carousel
  ================================================== -->

  <div class="col-caroussel-yogis">      
    <div id="myCarousel" class="carousel slide" data-ride="carousel" style="vertical-align:middle;">
    
      <!-- Indicators -->
      <ol class="carousel-indicators" style="top:20px; height:200px">
      	<!-- en fonction du nombre de compagnie -->
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        {% if scene_photo_list %}
        {% for scene in scene_photo_list %}
        <!-- {% if scene.photo_gallery.photos %}   -->
        <li data-target="#myCarousel" data-slide-to="{{forloop.counter}}"></li>
        <!-- {% endif %} -->
        {% endfor %}
        {% else %}<!-- cas de la page spectacle -->
        {% for photo in scene.photo_gallery.photos.all %}
        <li data-target="#myCarousel" data-slide-to="{{forloop.counter}}"></li>
        {% endfor %}
        {% endif %}
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">  
          {% if cover %}  
          <a href=""><img src="{{ cover.0.get_display_url }}" class="thumbnail" alt="" style="width: 100%; height: 100%";></a>
          {% else %}
          <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Cover" >
          {% endif %}
          <div class="container">
            <div class="carousel-caption" style="top:20px;">
              <h1>Catalogue des spectacles</h1>
              <p>{{ company_list|length }} compagnies et {{ scene_list|length }} spectacles </p>
              <a class="btn btn-lg btn-default" href="{% url 'catalog:newsletter' %}" role="button" style="margin-top: 20px;">Newsletter</a>
            </div><!-- carousel-caption-->
          </div> <!-- container -->
        </div> <!-- class item active -->
        {% if scene_list %}
        {% for scene in scene_list %}
        {% if scene.photo_gallery.photos.all %}
        <div class="item">
          {% with scene.photo_gallery.photos.all|random as photo %}
          <a href="scene/{{ scene.id }}"><img src="{{ photo.get_display_url }}" class="thumbnail" alt="{{ photo.title }}" style="width: 100%; height: 100%;"></a>
          {% endwith %} 
        </div><!-- class item -->
        {% endif %}
        {% endfor %}
        {% else %}<!-- cas de la page spectacle -->
        {% for photo in scene.photo_gallery.photos.all %}
        <div class="item">
          <a href="scene/{{ scene.id }}"><img src="{{ photo.get_display_url }}" class="thumbnail" alt="{{ photo.title }}" style="width: 100%; height: 100%;"></a>
        </div><!-- class item -->       
        {% endfor %}
        {% endif %}
      </div><!-- carousel inner -->

      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Précedent</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Suivant</span>
      </a>
    </div><!-- mycarousel -->
  </div><!-- END Carousel   ================================================== -->

agence/catalogue/templates/catalogue/contact.html
{% extends "./base/base.html" %}
{% block content %}

{{ flatpage.content }}
{% endblock content %}

agence/catalogue/templates/catalogue/detail.html
{% extends "./base/base.html" %}

{% block content %}
<div class="row">
  {% block carousel %}
  {% include "./catalogue/carousel.html" %}
  {% endblock carousel %}
  <!--SIDEBARE-->
  <div class="col-sidebar-cie-yogis" style="float:right; padding-right:40px"  id="sidebar">
    <img class="img-rounded" style="margin-top: 10px" src="{{ company.logo.get_thumbnail_url }}" class="thumbnail" alt="{{ company.logo.title }}">
  </div>

    <!--COLONE CENTEALE SPECTACLE--> 
  <div class="col-spectacle-yogis" style="float:right;  padding-right:40px">
    <div class="jumbotron-yogis">
      <h1>{{ company.name }}</h1>
      {% if company.scene_set.all|length > 1 %}		
      <p>{{ company.scene_set.all|length }} spectacles</p>
      {% else %}
      <p>{{ company.scene_set.all|length }} spectacle</p>
      {% endif %}
      {% if company.resume %}
      <p>{{ company.resume }}</p>
      {% endif %}
    </div>  <!-- jumbotron-->

    <ul  class="list-inline" class="thumbnails"> 
      {% for scene in scene_list %}

      <li class="col-md-5"  style="width : 33%; ">
       <div class="thumbnail-yogis" style="margin-left: 20%; margin-right: 20%; margin-bottom:20px"> 


         {% if scene.photo_gallery.photos.all %}			
         {% with scene.photo_gallery.photos.all|random as photo %}
         <a href="{%  url 'catalog:detail_scene' scene.id %}" class="list-group-item-yogis" style="height:200px"><img class="img-circle" src="{{ photo.get_thumbnail_url  }}" class="thumbnail" alt="{{ photo.title }}">
           {% endwith %}
           {% else %}
           <a href="{%  url 'catalog:detail_scene' scene.id %}" class="list-group-item-yogis" style="height:200px"><img class="img-circle" src="{{ compagny.logo.get_thumbnail_url }}" class="thumbnail-yogis" alt="{{ company.logo.title }}">
             {% endif %}
             <h4>{{ scene.title }}</h4></a>		      

           </div><!-- thumbnail -->
         </li>
         {% endfor %}
       </ul>


       <!-- START THE FEATURETTES -->

       <div class="row featurette"></div>
       <hr class="featurette-divider">
       <div class="row featurette">

        <div class="col-md-7">
          <h2 class="featurette-heading">
            Ateliers proposés <span class="text-muted">en plus des spectacles</span></h2>
            <p class="lead">
             {% if company.workshop_describe %} {{ company.workshop_describe }}{% endif %}
             {% if company.workshop_price %}<p>{{ company.workshop_price }}{% endif %}
             {% if company.workshop_term %}{{ company.workshop_term }}{% endif %}</p>
           </div>

           <div class="col-md-5">
            <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
          </div>
        </div>


        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-5">
            <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
          </div>
          <div class="col-md-7">
            <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">
      </div><!-- class="col-xs-12 col-sm-9-->
      <!-- /END THE FEATURETTES -->
      
     
   </div>
   {% endblock content %}

agence/catalogue/templates/catalogue/home.html
{% extends "./base/base.html" %}
{% block home %}
<div class="inner cover" >
	<h1 class="cover-heading">{{ flatpage.title }}</h1>
	<p class="lead">{{ flatpage.content }}</p>
	<p class="lead">
		<a href="/catalog" class="btn btn-lg btn-default">Entrer</a>
	</p>
</div>
{% endblock home %}   

agence/catalogue/templates/catalogue/index.html
{% extends "./base/base.html" %}


{% block content %}
    <div class="row">
    	{% block carousel %}
		{% include "./catalogue/carousel.html" %}
		{% endblock carousel %}
		<div class="col-sidebar-cie-yogis" id="sidebar">
			<div class="jumbotron-yogis">
				<h3>Les compagnies</h3>
			</div>  <!-- jumbotron-->
			{% for company in company_list %}
			<a href="{% url 'catalog:detail_company' company.id %}" class="list-group-item-sidebar-yogis" style="margin-top:10px ; height : auto; width:auto">
				<img class="img-rounded" src="{{ company.logo.get_thumbnail_url }}" alt="{{ company.logo.title }}" style ="height : auto; width:auto" >
			</a>
			<a href="{% url 'catalog:detail_company' company.id %}" class="list-group-item-sidebar-yogis" style="margin-top:10px ; height : auto; width:auto">{{ company.name }}</a>
			{% endfor %}
		</div><!--END SIDEBAR-->
        <div class="col-spectacle-yogis">
        	<div class="jumbotron-yogis">
        		<h1>Les spectacles</h1> 
        	</div>  <!-- jumbotron-->
  			<ul  class="list-inline" class="thumbnails-yogis"> 
				{% for company in company_list %}
					{% for scene in company.scene_set.all %}
						<li class="col-md-5" style="width : 33%">
						
						<div class="thumbnail-yogis"> 
							<div>
							{% if scene.photo_gallery.photos.all %}
								{% with scene.photo_gallery.photos.all|random as photo %}					 
							 	<a href="{%  url 'catalog:detail_scene' scene.id %}" class="list-group-item-yogis" style="height:200px"><img class="img-circle" src="{{ photo.get_thumbnail_url }}" style="height : auto; width:auto" class="thumbnail-yogis" alt="{{ company.logo.title }}">
							 	{% endwith %}
							 {% else %}
							 	<a href="{%  url 'catalog:detail_scene' scene.id %}" class="list-group-item-yogis" style="height:200px"><img class="img-circle" src="{{ compagny.logo.get_thumbnail_url }}"  style="height : auto; width:auto" class="thumbnail-yogis" alt="{{ company.logo.title }}">
							 {% endif %}
							 <h5>{{ scene.title }}</h5>
								</a>
							</div>
							{% endfor %}	
							{% empty %}
							<p>Désolé, aucune compagnie n'est disponible</p>
							{% endfor %}
						</div><!-- thumbnail -->
		</div><!-- col-SPECTACLE-->
		
	</div><!--/row-->
{% endblock content %}

agence/catalogue/templates/catalogue/newsletter.html
{% extends "./base/base.html" %}
{% block content %}



<div class="container">
 <div class="row">
<div class="col-sm-6 col-md-4 col-md-offset-4">
<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">

<div id="mc_embed_signup">
<form action="//alwaysdata.us10.list-manage.com/subscribe/post?u=96368c7caece79379c53a0b0c&amp;id=008f3df277" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
  <h2>S'inscrire à notre newsletter</h2>
<div class="indicates-required"><span class="asterisk">*</span> champs requis</div>
<div class="mc-field-group">
  <label for="mce-EMAIL">Adresse Email <span class="asterisk">*</span>
</label>
  <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" style="color: black;">
</div>
<div class="mc-field-group">
  <label for="mce-FNAME">Prénom </label>
  <input type="text" value="" name="FNAME" class="" id="mce-FNAME" style="color: black;">
</div>
<div class="mc-field-group">
  <label for="mce-LNAME">Nom </label>
  <input type="text" value="" name="LNAME" class="" id="mce-LNAME" style="color: black;">
</div>
<p><a href="http://us10.campaign-archive2.com/home/?u=96368c7caece79379c53a0b0c&id=008f3df277" title="View previous campaigns">Voir les précédentes newsletters</a></p>
  <div id="mce-responses" class="clear">
    <div class="response" id="mce-error-response" style="display:none"></div>
    <div class="response" id="mce-success-response" style="display:none"></div>
  </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_96368c7caece79379c53a0b0c_008f3df277" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>

</div>
</div>
</div>
</div>
{% endblock content %}

agence/catalogue/templates/catalogue/pro.html
{% extends "./base/base.html" %}
{% load render_table from django_tables2 %}
{% block content %}
<div class="fluid-container">
	<div class="row">
		{% if pro == True %}
		<p><a class="btn btn-xs btn-default" style="text-align:right" href="../proLight" role="button">Voir formule réduite</a></p>
		{% else %}
		<p><a class="btn btn-xs btn-default" href="../pro" role="button">Voir formule complète</a></p>
		{% endif %}
	</div>

	<div class="row">
		{% render_table scene_table %}
	</div>
</div>
{% endblock content %}